### ISSUE TITLE
Mopping function doesn't work

### ISSUE THREAD

**Issue by Theoreet** [congatudo/congatudo-add-on#26]
Tried the "water drop" mopping function, but none of the options give/drops some water. Tested the water pump motor within the special water dustbin and this motor is working fine .

Also when a open the home page its always possible to change this drop from off to all other 3 options even when the water bin isn't installed

**Comment by adrigzr** [comment]
Hi @Theoreet, 

What Conga model are you using? I only tested the mop function on the 3490 and the water drop is working fine. 

The water drop option in the retail app is blocked unless you has the right attachment, but this is imposible to implement in Valetudo. The underlying implementation of the feature in the robot allows to be changed besides the attachment not being the water tank so it is working "as expected".

Have you tested the water drop function with the retail app?

Regards,

**Comment by Theoreet** [comment]
Hi

Using the 3590

Op za 8 jan. 2022 12:54 schreef Adrián González Rus <
***@***.***>:

**Comment by elraro** [comment]
Please, try the beta addon.

If you still have problems, open a issue in Congatudo repository: https://github.com/congatudo/Congatudo
