### ISSUE TITLE
Valetudo UI not working. Logs in Docker showing "Cannot read property 'toString' of null"

### ISSUE THREAD

**Issue by joaquinvacas** [congatudo/congatudo-add-on#29]
Hi there :wave: 

Running Valetudo latest from your Docker image.
Using a Cecotec Conga 3090. 

Apparently, it recognizes the vacuum, the problem here it's the server reports a problem as soon as you open the web UI.

It keeps loading and the logs report an _unhandledRejection_ throwing _reason: TypeError: Cannot read property 'toString' of null_

Check attached logs for more info.

[_valetudo_logs (1).txt](https://github.com/freeconga/congatudo-add-on/files/8068268/_valetudo_logs.1.txt)

**Comment by txitxo0** [comment]
Check your your configuration file (valetudo.json) it seems like you have the embebed property in true, instead of false. 

Maybe congatudo couldn't handle the installation well. Do you have the mqtt server through the ha integration? Or do you have another one else?
