### ISSUE TITLE
5090 doesn't ask to neither lets me to save map

### ISSUE THREAD

**Issue by jjaammhh** [congatudo/congatudo-add-on#32]
Hi,

I have a setup with CongaTudo 2022.2 enabled via HomeAssistant addon, and a Conga 5090 connected to it.

The first time it ended my full house a Valetudo event asdked me if I wanted to save map. I answered yes.

A couple of days after, I deleted persistent map info via Valetudo button, and the map was succesfully deteled.

But now, it doesn't ask me to save map when it returns to dock any longer. And I can't see any option to manually force it to persist last map.

Is there anything I can check?

Thanks

**Comment by txitxo0** [comment]
I am not quite sure (I don't have this conga model) but, did you try by a full cleaning in low fan speed? In my model it triggers the keeping map state.

Try triggering a new full cleaning up with this fan speed and check the events out ;)

**Comment by jjaammhh** [comment]
Thanks for your idea, but that's precisely the mode in which I make my cleanings.

I've tried low fan with 0 water usage and low fan with high water usage, with the same result :-(

**Comment by elraro** [comment]
This issue is old from the legacy frontend. Please, if you have problems with the new beta version, open a issue in Congatudo repository: https://github.com/congatudo/Congatudo
