### ISSUE TITLE
Cannot manually start a mapping pass, and rest call returns "Cannot PUT /api/v2/robot/capabilities/MappingPassCapability" with Conga 5090

### ISSUE THREAD

**Issue by jjaammhh** [congatudo/congatudo-add-on#33]
Hi,

I have a setup with CongaTudo 2022.2 enabled via HomeAssistant addon, and a Conga 5090 connected to it.

I can't invoke a mapping pass "cleaning". Valetude UI doesn't offer such option, and, when I try to invoke it by a rest API call, I obtaing a "Cannot PUT /api/v2/robot/capabilities/MappingPassCapability" message:

CALL:

curl -X 'PUT' \
  'https://mySuperHouse/api/hassio_ingress/541jCKfsFvX0qfofDn2IBt9rTDbPit8jLLRoGD4z6AY/api/v2/robot/capabilities/MappingPassCapability' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "action": "start_mapping"
}'

RESPONSE:

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot PUT /api/v2/robot/capabilities/MappingPassCapability</pre>
</body>
</html>

Vacuum Model
Conga 5090

Valetudo Version
2022.2.0

**Comment by elraro** [comment]
Please, try the beta addon.

If you still have problems, open a issue in Congatudo repository: https://github.com/congatudo/Congatudo
