### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by n1ete** [congatudo/congatudo-add-on#38]
Is this still maintained? 
besides of the issues with the 5090 model it would be nice to see regular updates to this......

**Comment by ZZJHONS** [comment]
I would like to know too, this repo is the only reference I found on the internet that could have possibilities to connect Conga 6090 to Home Assistant, I can do tests and share data emitted if needed by any dev.

**Comment by elraro** [comment]
Hello,

We are working on this. You can visit our Telegram group: https://t.me/congatudo
