### ISSUE TITLE
Cannot edit Segments

### ISSUE THREAD

**Issue by EzeLamar** [congatudo/congatudo-add-on#39]
## Describe the bug
Hi,
I cannot rename, split or merge Segments using the UI. When I try to do that I got the next error:
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/26080561/218289422-379d42ea-5bc6-413c-8019-4967808b8ff6.png">
And in the logs I got the next warning (rename action):
```
2023-02-12T02:18:31.334Z
Warn
Received "PUT "to "/api/v2/robot/capabilities/MapSegmentRenameCapability" with invalid payload [
  {
    keyword: 'type',
    dataPath: '.segment_id',
    schemaPath: '#/properties/segment_id/type',
    params: { type: 'string' },
    message: 'should be string'
  }
]
```

## To Reproduce
1. Create a new map by zero
2. Try to edit a Segment
3. See error

### Vacuum Model
Conga 3490

### Congatudo-Add-On Version
0.2.5 - 2022-10-21 (latest version)

Thanks!

**Comment by elraro** [comment]
Hi @EzeLamar !

Please, try the new release of the Congatudo addon 2023.02.0

**Comment by txitxo0** [comment]
Anyway, this has to be a bug related to congatudo, not congatudo addon. Just to be clean and organiced

**Comment by EzeLamar** [comment]
Thanks @elraro for the quick answer!
I will try it as soon as it is available

**Comment by Nismonx** [comment]
@EzeLamar 
It's very finicky with the last 2 releases, you have to click in the green lines ( not all of them work ) at least it's how I get around on my 4090. Not very practical if you use the congatudo interface 
![Screenshot_20230212_170754_Home Assistant](https://user-images.githubusercontent.com/62077532/218325925-1023d2d3-a045-4ac5-86d1-d65913d5a280.jpg)

**Comment by Nismonx** [comment]
Actually now that I have read it again, my explanation above is irrelevant to your issue 🤦‍♂️

**Comment by EzeLamar** [comment]
Thanks @Nismonx! I was fighting with the UI for a while until I figured out that I should click on the green lines 😅 
Everything is working again and my segments were successfully configured. @elraro, you rock!

**Comment by elraro** [comment]
Hi @EzeLamar .

Can you share a screenshot of your map? Do you see the segments?

**Comment by EzeLamar** [comment]
Sure @elraro, I can see and edit the segments without any problem (tested join, add cutting lines and rename it). I attach a screenshot showing the problem solved. 
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/26080561/218342407-efbb61c4-a227-4fdf-8c87-fc0166b45337.png">
Segments renamed:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/26080561/218342519-22c5c773-7d7f-47ed-872e-775b1b61a77e.png">

**Comment by Nismonx** [comment]
@EzeLamar if you want to send the conga to clean lets say the 'Living' are you able to do so just by touching the triange or do you have to touch in the green lines?

**Comment by EzeLamar** [comment]
@elraro unfortunately, the only way is touching the green line, the triangle doesn't work.

**Comment by Nismonx** [comment]
Not very practical therefore the issue still persist despite the little work around to get things done.
Hopefully @elraro and the team will find a solution 🤞

**Comment by elraro** [comment]
Hi, please update your addons with the new version Congatudo 2023.03.0 in beta channel

**Comment by elraro** [comment]
Hello,

Can you try the beta addon @EzeLamar ? If you still have problems, open a issue in https://github.com/congatudo/Congatudo
