### ISSUE TITLE
After update Conga 4090 malfunctioning

### ISSUE THREAD

**Issue by angelitoo776** [congatudo/congatudo-add-on#41]
Version: 2023.02.0
Hardware : NUC

Description:
After the update the conga 4090 malfunctions.
It seems that it stays in manual mode and goes constantly forward.

**Comment by elraro** [comment]
Can you try the new Congatudo 2023.03.0 in beta channel?

**Comment by angelitoo776** [comment]
I have installed. 
I will test it today and I will let you know if the error appears.

**Comment by elraro** [comment]
Any news?

**Comment by elraro** [comment]
Any news @angelitoo776 ?

Please, open this issue in https://github.com/congatudo/Congatudo repository
