### ISSUE TITLE
Revert host file

### ISSUE THREAD

**Issue by RoomControl18** [congatudo/congatudo-add-on#47]
Hello. 

I overwrote the file host with 

echo " 'your home assistant ip' cecotec.das.3irobotix.net cecotec.download.3irobotix.net cecotec.log.3irobotix.net cecotec.ota.3irobotix.net eu.das.3irobotics.net eu.log.3irobotics.net eu.ota.3irobotics.net cecotec-das.3irobotix.net cecotec-log.3irobotix.net cecotec-upgrade.3irobotix.net cecotec-download.3irobotix.net" >> /etc/hosts

Since i did, i have issues to use the conga robot with the Cecotec original app. What should I do to revert the file to the original configuration? maybe: 

 echo "cecotec.das.3irobotix.net cecotec.download.3irobotix.net cecotec.log.3irobotix.net cecotec.ota.3irobotix.net eu.das.3irobotics.net eu.log.3irobotics.net eu.ota.3irobotics.net cecotec-das.3irobotix.net cecotec-log.3irobotix.net cecotec-upgrade.3irobotix.net cecotec-download.3irobotix.net" >> /etc/hosts

Thanks in advance.

**Comment by txitxo0** [comment]
Please, refer to his doc https://github.com/congatudo/stuff/blob/master/docs/stepbystep-valetudo-installation.md

Uninstall valetudo step, in you case, as you don't have a standalone installation, just the third command, the sed one
