### ISSUE TITLE
2299 compatibility

### ISSUE THREAD

**Issue by miyoda** [congatudo/congatudo-add-on#50]
Is it possible to have compatibility with the conga 2299 model?
https://cecotec.es/es/robots-aspiradores/conga-2299-ultra-home-x-treme

**Comment by elraro** [comment]
Hi,

This issue is related to https://github.com/congatudo/agnoc.

First, we will try to add support to 6090 with SSL protocol. We don't know what type of protocol use the 2299 model.

Please, open the issue in agnoc repository.
