### ISSUE TITLE
Map save?

### ISSUE THREAD

**Issue by yorchtf** [congatudo/congatudo-add-on#51]
Hi,

Guys, a simple question... does it happen to you that every time the conga goes off you lose the map of the house in home assistant?

<img width="821" alt="image" src="https://github.com/congatudo/congatudo-add-on/assets/8900958/60e3e53b-54b9-41c8-90e7-92b3927cd53a">

In the map configuration, I have selected "persisten maps" option.

<img width="565" alt="image" src="https://github.com/congatudo/congatudo-add-on/assets/8900958/6ad36569-cfad-41fa-a6b8-26ae1c3960a1">

Regards,

**Comment by Nismonx** [comment]
It's not unheard of losing maps but not at every power cycle.
Can you elaborate on you setup?

**Comment by yorchtf** [comment]
Hi,

The problem happen when turn off  base of conga or the conga finish his battery.

For example, the first time that the device scan then rooms and then robot create the map. Here not problem. After that,  I run conga again to clean then rooms and then map work fine, but the night arrive and turn off the conga device to save energy and money. In the next morning turn on it and in the home assistant is not a map.

Conga 4092
Home assistant: 2023.5

If you want, I could write in spanish.

Regards

**Comment by Nismonx** [comment]
Please keep it in English....

Did you saved the first map?
After the first clean, it will generate a map. Then in the Conga integration it should ask you if you want to save the map, (top left corner red bell)  if you don't do this it will keep wipe the map. Sometimes it takes a couple of minutes for it to show up.

Also there's no point in keep turning it off, all you are going to achieve is a lot of problems an eventually system corruption.  And you are not saving any energy the all with the issues it is causing. When the conga is not in use it will go in to sleep (low energy mode)

**Comment by yorchtf** [comment]
I understand that if you turned off the equipment, it is normal for the problem I mentioned to occur.  ?

I think that would be another discussion if turn off allow save energy or money.

**Comment by yorchtf** [comment]
Sorry, i forgot answer your first question. Yes, always save the map (click on the red bell)

**Comment by Nismonx** [comment]
> I understand that if you turned off the equipment, it is normal for the problem I mentioned to occur. ?
> 
> I think that would be another discussion if turn off allow save energy or money.

Turning something OFF that was designed to be ON all the time is probably not  going to help troubleshooting your issue.

You can check is the map is still in the conga by ssh to it.

I own a 4090 and only ever lost maps once or twice but that's because I was playing around with my setup.

If your conga is running out of battery then you definitely have some other problems or are miss using it by the sound of it. 

Do you also turn off your HA server when not ussing it 👀

This is not an issue related to congatudo integration and you are better of getting some help in the telegram group. ( link above )

**Comment by yorchtf** [comment]
Ok the congatudo work fine... BEST support.... Congratulations

**Comment by yorchtf** [comment]
Great support

**Comment by elraro** [comment]
Please, open an issue in Congatudo repository (not here in the addon repo), and attach logs.

Also, try to avoid the irony.

**Comment by txitxo0** [comment]
Anyway, maps are stored in the conga itself, not in congatudo or congatudo-addon, so I guess we can not do much more in here.

And yes, irony is completely misplaced. This is an open project where everybody can take part, even you. There is no active support apart of some people in their free time.

Regards
