### ISSUE TITLE
Any way to connect a Cecotec fan to home assistant?

### ISSUE THREAD

**Issue by D4llo** [congatudo/congatudo-add-on#55]
like those one:
- https://www.amazon.fr/gp/product/B0BQ1WVQS4/ref=ox_sc_act_title_2?smid=A1X6FK5RDHNB96
- https://www.amazon.fr/dp/B0BPYX56WM/ref=sbl_dpx_fr-lighting-ceiling-fans_B0BQ1WVQS4_0?th=1

**Comment by Nismonx** [comment]
Really!?

No, not that we know of....

Maybe you can use some IR blaster to control the fan or if it uses an RF remote, then you have to look at a different alternative.

Listing the spec's would help but that would be off topic here anyway.

Good luck

**Comment by D4llo** [comment]
> Really!?

yeah

> You do know the difference between a vacuum cleaner and a fan right?

What do you think?

> Did you even look to see what congatudo is about?

Yes!


----

> No, not that we know of....

Thank you for answering. I was hoping that the Cecotec brand used an unified API and that I could fork this project and adapt it to make it work for their fan.

> Also this is not an issue but a feature request (sort of)

Issue are fine for feature request most of the time. As maintainer you can do whatever you want though.

> You'll have better luck ask the HA community

I will do that. Thank you :)

**Comment by txitxo0** [comment]
> > Really!?
> 
> yeah
> 
> > You do know the difference between a vacuum cleaner and a fan right?
> 
> What do you think?
> 
> > Did you even look to see what congatudo is about?
> 
> Yes!
> 
> 
> ----
> 
> > No, not that we know of....
> 
> Thank you for answering. I was hoping that the Cecotec brand used an unified API and that I could fork this project and adapt it to make it work for their fan.
> 
> > Also this is not an issue but a feature request (sort of)
> 
> Issue are fine for feature request most of the time. As maintainer you can do whatever you want though.
> 
> > You'll have better luck ask the HA community
> 
> I will do that. Thank you :)
> 

Anyway, congatudo serves a new server. I don't know how is this fan working but I think there is no relationship between features. Maybe the auth?? I don't really know and we just avoid it using a mitm server. So this repo is not what you are looking.

Normally fans use RF communication with the remote, so you always try to do your best with a broad link rm4 pro (i.e.)
